const dummyData = [
    {
        id: 1,
        pfp_url: '/assets/pfp_user.png',
        name: 'Hiro Joyce',
        role: 'Senior UX/UI Designer',
        tag: 'Qualified Lead',
        company: 'TTB Bank',
        location: 'Bangkok',
        details: 'UX/UI designer in Bangkok',
        lastMessage: {
            text: 'Looking forward to our next meeting!',
            time: '08:17 AM',
            date: 'Jan 10',
        },
        campaignId: 8,
        campaign: 'Summer UX Con 2021',
        sender: {
            name: 'Alison Brie',
            image: '/assets/pfp_sender.png',
        },
        status: {
            unread: false,
            unreplied: false,
            drafting: true,
        },
        selected: false,
    },
    {
        id: 2,
        pfp_url: '/assets/pfp_user.png',
        name: 'Jane Doe',
        company: 'Lineman',
        location: 'Bangkok',
        role: 'Product Manager',
        tag: 'Interested',
        details: 'Product manager at Tech Solutions',
        lastMessage: {
            text: 'Can you send over the files?',
            time: '19:42 AM',
            date: 'Jan 9',
        },
        campaignId: 16,
        campaign: 'Product Launch Q1 2023',
        sender: {
            name: 'Dave Franco',
            image: '/assets/pfp_sender.png',
        },
        status: {
            unread: true,
            unreplied: true,
            drafting: false,
        },
        selected: false,
    },
    {
        id: 3,
        pfp_url: '/assets/pfp_user.png',
        name: 'Peter Park',
        company: 'Agoda',
        location: 'New York',
        role: 'Developer',
        tag: 'Not Interested',
        details: 'Product manager at Tech Solutions',
        lastMessage: {
            text: 'Can you send over the files?',
            time: '09:32 AM',
            date: 'Jan 9',
        },
        campaignId: 1,
        campaign: 'Product Launch Q1 2021 B',
        sender: {
            name: 'Dave Franco',
            image: '/assets/pfp_sender.png',
        },
        status: {
            unread: true,
            unreplied: false,
            drafting: false,
        },
        selected: false,
    },
    {
        id: 4,
        company: 'TTB Bank',
        location: 'Bangkok',
        pfp_url: '/assets/pfp_user.png',
        name: 'Saw Zwe',
        role: 'Full Stack Developer',
        tag: 'Referral',
        details: 'Product manager at Tech Solutions',
        lastMessage: {
            text: 'Can you send over the files?',
            time: '09:54 AM',
            date: 'Jan 9',
        },
        campaignId: 1,
        campaign: 'Product Launch Q1 2021',
        sender: {
            name: 'Dave Franco',
            image: '/assets/pfp_sender.png',
        },
        status: {
            unread: true,
            unreplied: true,
            drafting: false,
        },
        selected: false,
    },
    {
        id: 5,
        pfp_url: '/assets/pfp_user.png',
        name: 'Hiro Joyce',
        role: 'Senior UX/UI Designer',
        tag: 'Qualified Lead',
        company: 'TTB Bank',
        location: 'Bangkok',
        details: 'UX/UI designer in Bangkok',
        lastMessage: {
            text: 'Looking forward to our next meeting!',
            time: '08:17 AM',
            date: 'Jan 10',
        },
        campaignId: 8,
        campaign: 'Summer UX Con 2021',
        sender: {
            name: 'Alison Brie',
            image: '/assets/pfp_sender.png',
        },
        status: {
            unread: false,
            unreplied: false,
            drafting: true,
        },
        selected: false,
    },
    {
        id: 6,
        pfp_url: '/assets/pfp_user.png',
        name: 'Jane Doe',
        company: 'Lineman',
        location: 'Bangkok',
        role: 'Product Manager',
        tag: 'Interested',
        details: 'Product manager at Tech Solutions',
        lastMessage: {
            text: 'Can you send over the files?',
            time: '19:42 AM',
            date: 'Jan 9',
        },
        campaignId: 16,
        campaign: 'Product Launch Q1 2023',
        sender: {
            name: 'Dave Franco',
            image: '/assets/pfp_sender.png',
        },
        status: {
            unread: true,
            unreplied: true,
            drafting: false,
        },
        selected: false,
    },
    {
        id: 7,
        pfp_url: '/assets/pfp_user.png',
        name: 'Peter Park',
        company: 'Agoda',
        location: 'New York',
        role: 'Developer',
        tag: 'Not Interested',
        details: 'Product manager at Tech Solutions',
        lastMessage: {
            text: 'Can you send over the files?',
            time: '09:32 AM',
            date: 'Jan 9',
        },
        campaignId: 1,
        campaign: 'Product Launch Q1 2021 B',
        sender: {
            name: 'Dave Franco',
            image: '/assets/pfp_sender.png',
        },
        status: {
            unread: true,
            unreplied: false,
            drafting: false,
        },
        selected: false,
    },
    {
        id: 8,
        company: 'TTB Bank',
        location: 'Bangkok',
        pfp_url: '/assets/pfp_user.png',
        name: 'Saw Zwe',
        role: 'Full Stack Developer',
        tag: 'Referral',
        details: 'Product manager at Tech Solutions',
        lastMessage: {
            text: 'Can you send over the files?',
            time: '09:54 AM',
            date: 'Jan 9',
        },
        campaignId: 1,
        campaign: 'Product Launch Q1 2021',
        sender: {
            name: 'Dave Franco',
            image: '/assets/pfp_sender.png',
        },
        status: {
            unread: true,
            unreplied: true,
            drafting: false,
        },
        selected: false,
    },
    {
        id:11,
        pfp_url: '/assets/pfp_user.png',
        name: 'Peter Park',
        company: 'Agoda',
        location: 'New York',
        role: 'Developer',
        tag: 'Not Interested',
        details: 'Product manager at Tech Solutions',
        lastMessage: {
            text: 'Can you send over the files?',
            time: '09:32 AM',
            date: 'Jan 9',
        },
        campaignId: 1,
        campaign: 'Product Launch Q1 2021 B',
        sender: {
            name: 'Dave Franco',
            image: '/assets/pfp_sender.png',
        },
        status: {
            unread: true,
            unreplied: false,
            drafting: false,
        },
        selected: false,
    },
    {
        id: 10,
        company: 'TTB Bank',
        location: 'Bangkok',
        pfp_url: '/assets/pfp_user.png',
        name: 'Saw Zwe',
        role: 'Full Stack Developer',
        tag: 'Referral',
        details: 'Product manager at Tech Solutions',
        lastMessage: {
            text: 'Can you send over the files?',
            time: '09:54 AM',
            date: 'Jan 9',
        },
        campaignId: 1,
        campaign: 'Product Launch Q1 2021',
        sender: {
            name: 'Dave Franco',
            image: '/assets/pfp_sender.png',
        },
        status: {
            unread: true,
            unreplied: true,
            drafting: false,
        },
        selected: false,
    },
];

export default dummyData;
